### ISSUE TITLE
array out-of-bounds access in tst_env_get_version.c:36 due to incorrect loop bounds

### ISSUE THREAD

**Issue by BenWibking** [open-mpi/mpi-test-suite#9]
AddressSanitizers shows an array-of-out-bounds access at `env/tst_env_get_version.c:36`:

```
Environment tests Get_version (4/101), comm MPI_COMM_SELF (3/9), type MPI_CHAR (1/29)
=================================================================
==13945==ERROR: AddressSanitizer: stack-buffer-overflow on address 0xffffdf280430 at pc 0x00000041a414 bp 0xffffdf280310 sp 0xffffdf280328
READ of size 4 at 0xffffdf280430 thread T0
    #0 0x41a410 in tst_env_get_version_run env/tst_env_get_version.c:36
    #1 0x407c58 in main /home/benwibking.linux/mpi-test-suite/mpi_test_suite.c:456
    #2 0xffffb282b584 in __libc_start_call_main (/lib64/libc.so.6+0x2b584)
    #3 0xffffb282b65c in __libc_start_main@@GLIBC_2.34 (/lib64/libc.so.6+0x2b65c)
    #4 0x40992c in _start (/home/benwibking.linux/mpi-test-suite/mpi_test_suite+0x40992c)

Address 0xffffdf280430 is located in stack of thread T0 at offset 128 in frame
    #0 0x41a0e0 in tst_env_get_version_run env/tst_env_get_version.c:26

  This frame has 5 object(s):
    [32, 36) 'version' (line 27)
    [48, 52) 'subversion' (line 28)
    [64, 68) 'err_string_len' (line 30)
    [80, 128) 'valid_mpi_versions' (line 33) <== Memory access at offset 128 overflows this variable
    [160, 672) 'err_string' (line 30)
   ```

By inspection, we can see that this is due to incorrect loop bounds at `env/tst_env_get_version.c:35`.

```
  int valid_mpi_versions[][2] = { {3,1}, {3,0}, {2,2}, {2,1}, {2,0}, {1,2} };
  int i;
  for( i = 0; i < sizeof(valid_mpi_versions); i++) {
    if( valid_mpi_versions[i][0] == version && valid_mpi_versions[i][1] == subversion) {
      return 0;
    }
  }
```

**Comment by cniethammer** [comment]
Thanks for reporting.

Fixed by #10
